#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/bspwm"
STYLE="ultranumb"
RASI="$DIR/themes/$STYLE/rofi/launcher.rasi"

# Run
# rofi \
#     -show drun \
# 	-kb-cancel Alt-F1 \
# 	-theme ${RASI}

rofi \
    -show drun \
	-kb-cancel 'Super_L+d,Alt+F1,Escape' \
	-theme ${RASI}
