#!/usr/bin/env bash

infocenter(){
FILE="$HOME/.cache/eww_dzhoga.dashboard"
DASHBOARD="$HOME/.config/bspwm/themes/ultranumb/eww/dashboard"

if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	eww --config $DASHBOARD open dashboard
else
	eww --config $DASHBOARD close dashboard
	rm "$FILE"
fi
}

calendar(){
LOCK_FILE="$HOME/.cache/eww-dzhoga-calendar.lock"
BAR="$HOME/.config/bspwm/themes/ultranumb/eww/bar"

if [[ ! -f "$LOCK_FILE" ]]; then
    touch "$LOCK_FILE"
    eww -c $BAR open calendar
else
    eww -c $BAR close calendar
    rm "$LOCK_FILE"
fi
}

case "$1" in
  --infocenter)
	infocenter;;
  --calendar)
	calendar;;
esac
